// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpidfenbclycjvdqloib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwaWRmZW5iY2x5Y2p2ZHFsb2liIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNzIwNzgsImV4cCI6MjA2MzY0ODA3OH0.QLxP3D4hCFuPxsy7J2x2cVah3tsNZdkYprG8bXCP6zo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);